[project]
name = "Python_BMP"
description = "A pure Python 2D/3D graphics library that outputs to windows bitmap format"
version = "0.9.1"
authors = [
    { name = "Joel Alcarez", email = "joelalcarez1975@gmail.com" }
]

license = {file = "LICENSE"}
readme = "README.md"

[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.