[project]
name = "pythonbmp_TECHNOTANUKI"
description = "A pure Python 2D/3D graphics library that outputs to windows bitmap format"
version = "0.9.1"
authors = [
    { name = "Joel Alcarez", email = "joelalcarez1975@gmail.com" }
]

license = {file = "LICENSE"}
readme = "README.md"
python = "^3.8"
homepage = "https://github.com/TechnoTanuki/Python_BMP"
repository = "https://github.com/TechnoTanuki/Python_BMP"
documentation = "https://github.com/TechnoTanuki/Python_BMP"

[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.